name: Validate Shell Script

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Shell Script
        run: |
          # Install shellcheck
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # Run shellcheck on the script
          shellcheck environment_setup.sh
          shellcheck performance-monitoring.sh
