name: Validate Shell Script

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate Shell Script
        run: |
          # Install shellcheck
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # Run shellcheck on the script
          find . -type f \( \
          -name "environment_setup.sh" -o \
          -name "performance-monitoring*.sh" \
          \) -print0 | xargs -0 -n1 shellcheck
